src/Entity/Spectacle.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpectacleRepository")
 */
class Spectacle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le titre est obligatoire")
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom de la compagnie est obligatoire")
     */
    private $nom_cie;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resume;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_cie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_video;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $critique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dossier;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dossier_peda;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Spectateur", inversedBy="spectacles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $spectateur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Categorie", inversedBy="spectacles")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SousCategorie", inversedBy="spectacles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $sousCategorie;

    /**
     * @Assert\Image(mimeTypesMessage="Le fichier doit être une image",
     * maxSize="1000k", maxSizeMessage="Le fichier ne doit pas faire plus de 1000ko")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image1;

    /**
     * @Assert\Image(mimeTypesMessage="Le fichier doit être une image",
     * maxSize="1000k", maxSizeMessage="Le fichier ne doit pas faire plus de 1000ko")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image2;

    /**
     * @Assert\Image(mimeTypesMessage="Le fichier doit être une image",
     * maxSize="1000k", maxSizeMessage="Le fichier ne doit pas faire plus de 1000ko")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image3;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $en_savoir_plus;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $texte_complementaire;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $en_tournee;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $departement;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $age_spectateurs;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mail_contact;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $representations;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note_mise_en_scene;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $atelier;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dimensions_plateau;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $en_pratique;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $pays;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $coproduction;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $sousCategoriePersonalise;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
    }







    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNomCie(): ?string
    {
        return $this->nom_cie;
    }

    public function setNomCie(string $nom_cie): self
    {
        $this->nom_cie = $nom_cie;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getSiteCie(): ?string
    {
        return $this->site_cie;
    }

    public function setSiteCie(?string $site_cie): self
    {
        $this->site_cie = $site_cie;

        return $this;
    }

    public function getUrlVideo(): ?string
    {
        return $this->url_video;
    }

    public function setUrlVideo(?string $url_video): self
    {
        $this->url_video = $url_video;

        return $this;
    }

    public function getCritique(): ?string
    {
        return $this->critique;
    }

    public function setCritique(?string $critique): self
    {
        $this->critique = $critique;

        return $this;
    }

    public function getDossier(): ?string
    {
        return $this->dossier;
    }

    public function setDossier(?string $dossier): self
    {
        $this->dossier = $dossier;

        return $this;
    }

    public function getDossierPeda(): ?string
    {
        return $this->dossier_peda;
    }

    public function setDossierPeda(?string $dossier_peda): self
    {
        $this->dossier_peda = $dossier_peda;

        return $this;
    }

    public function getSpectateur(): ?spectateur
    {
        return $this->spectateur;
    }

    public function setSpectateur(?spectateur $spectateur): self
    {
        $this->spectateur = $spectateur;

        return $this;
    }

    /**
     * @return Collection|categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }


    public function addCategorie(categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(categorie $categorie): self
    {
        if ($this->categorie->contains($categorie)) {
            $this->categorie->removeElement($categorie);
        }

        return $this;
    }

    public function getSousCategorie(): ?sousCategorie
    {
        return $this->sousCategorie;
    }

    public function setSousCategorie(?sousCategorie $sousCategorie): self
    {
        $this->sousCategorie = $sousCategorie;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage1()
    {
        return $this->image1;
    }

    /**
     * @param mixed $image1
     * @return $this
     */
    public function setImage1($image1)
    {
        $this->image1 = $image1;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage2()
    {
        return $this->image2;
    }

    /**
     * @param mixed $image2
     * @return $this
     */
    public function setImage2($image2)
    {
        $this->image2 = $image2;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage3()
    {
        return $this->image3;
    }

    /**
     * @param mixed $image3
     * @return $this
     */
    public function setImage3($image3)
    {
        $this->image3 = $image3;

        return $this;
    }

    public function getEnSavoirPlus(): ?string
    {
        return $this->en_savoir_plus;
    }

    public function setEnSavoirPlus(?string $en_savoir_plus): self
    {
        $this->en_savoir_plus = $en_savoir_plus;

        return $this;
    }

    public function getTexteComplementaire(): ?string
    {
        return $this->texte_complementaire;
    }

    public function setTexteComplementaire(?string $texte_complementaire): self
    {
        $this->texte_complementaire = $texte_complementaire;

        return $this;
    }

    public function getEnTournee(): ?string
    {
        return $this->en_tournee;
    }

    public function setEnTournee(?string $en_tournee): self
    {
        $this->en_tournee = $en_tournee;

        return $this;
    }

    public function getDepartement(): ?int
    {
        return $this->departement;
    }

    public function setDepartement(?int $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getAgeSpectateurs(): ?int
    {
        return $this->age_spectateurs;
    }

    public function setAgeSpectateurs(?int $age_spectateurs): self
    {
        $this->age_spectateurs = $age_spectateurs;

        return $this;
    }

    public function getMailContact(): ?string
    {
        return $this->mail_contact;
    }

    public function setMailContact(?string $mail_contact): self
    {
        $this->mail_contact = $mail_contact;

        return $this;
    }

    public function getRepresentations(): ?string
    {
        return $this->representations;
    }

    public function setRepresentations(?string $representations): self
    {
        $this->representations = $representations;

        return $this;
    }

    public function getNoteMiseEnScene(): ?string
    {
        return $this->note_mise_en_scene;
    }

    public function setNoteMiseEnScene(?string $note_mise_en_scene): self
    {
        $this->note_mise_en_scene = $note_mise_en_scene;

src/Form/SpectacleType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\SousCategorie;
use App\Entity\Spectacle;
use App\Entity\Spectateur;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpectacleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'titre',
                TextType::class,
                [
                    'label' => 'Titre du spectacle'
                ])
            ->add('nom_cie',
                TextType::class,
                [
                    'label' => 'Nom de la compagnie'
                  ])
            ->add('resume',
                CKEditorType::class,
                [
                    'label' => 'Resumé'
                  ])

            ->add('duree',
                IntegerType::class,
                [
                    'label' => 'Durée (en minutes)'
                  ])
            ->add('site_cie',
                UrlType::class,
                [
                    'label' => 'URL du site de la compagnie',
                    'required' => false
                  ])
            ->add('url_video',
                UrlType::class,
                [
                    'label' => 'URL de la video du spectacle',
                    'required' => false
                  ])
            ->add('critique',
                CKEditorType::class,
                [
                    'label' => 'Critique du spectacle',
                    'required' => false
                  ])
            ->add('dossier',
                UrlType::class,
                [
                      'label' => 'URL du dossier du spectacle',
                      'required' => false
                  ])
            ->add('dossier_peda',
                UrlType::class,
                  [
                      'label' => 'URL du dossier pédagogique du spectacle',
                      'required' => false
                  ])
            ->add('spectateur',
                EntityType::class,
                [
                    'label' => 'Public visé',
                    'class' => Spectateur::class,
                    'choice_label' => 'type',
                    'placeholder' => 'Choisissez un public'
                  ])


            ->add('categorie',
                  EntityType::class,
                  [
                      'label' => 'Catégorie',
                      'class' => Categorie::class,
                      'choice_label' => 'type',
                      'placeholder' => 'Choisissez une catégorie',
                      'required' => false,
                      'multiple' => true,
                  ])

            ->add('sousCategorie',
                EntityType::class,
                  [
                      'label' => 'Sous-catégorie',
                      'class' => SousCategorie::class,
                      'choice_label' => 'type',
                      'placeholder' => 'Choisissez une sous-catégorie',
                        'required' => false

                  ])
            ->add(
                'image1',
                //input de type file
                FileType::class,
                [
                    'label' => 'Photo de couverture',
                    'required' => false,
                ])
            ->add(
                'image2',
                FileType::class,
                [
                    'label' => 'Photo 2',
                    'required' => false,
                ])
            ->add(
                'image3',
                FileType::class,
                [
                    'label' => 'Photo 3',
                    'required' => false,
                ])
            ->add(
                'enSavoirPlus',
                CKEditorType::class,
                [
                    'label' => 'En savoir plus',
                    'required' => false,
                ]
            )
            ->add(
                'texteComplementaire',
                CKEditorType::class,
                [
                    'label' => 'Texte complémentaire',
                    'required' => false,
                ]
            )
            ->add(
                'enTournee',
                TextType::class,
                [
                    'label' => 'Nombre et role des personnes en tournée',
                    'required' => false,
                ]
            )
            ->add(
                'departement',
                IntegerType::class,
                [
                    'label' => 'N° département de la cie',
                    'required' => false,
                ]
            )
            ->add(
                'ageSpectateurs',
                IntegerType::class,
                [
                    'label' => 'Age à partir de',
                    'required' => false,
                ]
            )
            ->add(
                'mailContact',
                TextType::class,
                [
                    'label' => 'Mail du contact Derviche',
                    'required' => false,
                ]
            )
            ->add(
                'representations',
                CKEditorType::class,
                [
                    'label' => 'Date et lieu de representations',
                    'required' => false,
                ]
            )
            ->add(
                'noteMiseEnScene',
                CKEditorType::class,
                [
                    'label' => 'Note du metteur en scène ou du chorégraphe',
                    'required' => false,
                ]
            )
            ->add(
                'atelier',
                CKEditorType::class,
                [
                    'label' => 'Atelier autour du spectacle',
                    'required' => false,
                ]
            )
            ->add(
                'dimensionsPlateau',
                TextType::class,
                [
                    'label' => 'Dimension du plateau',
                    'required' => false,
                ]
            )
            ->add(
                'enPratique',
                TextareaType::class,
                [
                    'label' => 'En pratique',
                    'required' => false,
                ]
            )
            ->add(
                'pays',
                TextType::class,
                [
                    'label' => 'Pays de la cie',
                    'required' => false,
                ]
            )
            ->add(
                'coproduction',
                CKEditorType::class,
                [
                    'label' => 'Coproduction et Soutien',
                    'required' => false,
                ]
            )

            ->add(
                'sousCategoriePersonalise',
                TextType::class,
                [
                    'label' => 'Sous-catégorie personnalisée',
                    'required' => false,
                ]
            )

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Spectacle::class,
        ]);
    }
}

templates/spectacle/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Derviche Diffusion | Nos Spectacles{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" href="{{ asset('css/spectacle.css') }}">

{% endblock %}

{% block body %}

    <div class="container hauteurMin">
        <h2 class="mt-5">Nos Spectacles</h2>


        {##### Search form  ###}
        <a href="{{ path('app_spectacle_index') }}" class="btn btn-outline-info btn-flitre my-4 btn-sm">Retour aux spectacles</a>

        <a href="{{ path('app_spectacle_searchspectacle') }}" class="btn btn-outline-info btn-flitre my-4 btn-sm">Nouvelle recherche</a>



        <div class="card bg-light mb-3 filtre">
            <div class="card-body">
                {{ form_start(search_form) }}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(search_form.titre) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(search_form.nom_cie) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(search_form.categorie) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(search_form.sous_categorie) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(search_form.spectateur) }}
                    </div>
                    <div class="col-md-3">
                        {{ form_row(search_form.pays) }}
                    </div>
                    <div class="col-md-3">
                        {{ form_row(search_form.departement) }}

                    </div>
                </div>
                <div class="text-right">
                    <button class="btn btn-outline-info mt-4 btn-sm" type="submit">Rechercher</button>
                </div>

                {{ form_end(search_form)}}

            </div>
        </div>
        <div id="blocSearch">

            {% if spectaclesByRecherche is not empty %}

                <div class="d-md-inline-flex p-5 flex-wrap justify-content-between">
                    {% for spectacle in spectaclesByRecherche %}

                        <div class="card m-4" style="width: 18rem;">
                            <div class="">
                                <img class="card-img-top" src="{{ asset('images/spectacles/'~ spectacle.image1) }}" alt="Card image cap">
                            </div>
                            <div class="card-body">
                                <h5 class="card-title card-titre-spect">{{ spectacle.titre }}</h5>
                                <p class="card-text card-sstitre-spect">{{ spectacle.nomCie }}</p>
                                <a href="{{ path('app_spectacle_singlespectacle', {'id' : spectacle.id }) }}" class="btn btn-outline-info">En savoir plus</a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            {% else %}
                <p>Il n'y a actuellement pas de spectacle qui correspond à votre recherche.</p>
            {% endif %}

        </div>
    </div>


{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/spectacle.js') }}"></script>
{% endblock %}

templates/spectacle/single.html.twig
{% extends 'base.html.twig' %}



{% block title %}{{ spectacle.titre }} | Derviche Diffusion{% endblock %}



{% block body %}

<div class="container hauteurMin">

    <a class="btn btn-outline-info mt-5" href="{{ path('app_spectacle_index') }}">Retour à la liste de spectacle</a>



    <h6 class="mt-5 text-secondary">{{ spectacle.nomCie }}</h6>

    <h2 class="">{{ spectacle.titre }}</h2>

    <div class="row">
        <div class="col-md-8">
        {% for categ in spectacle.categorie %}
             {{ categ }} /
        {% endfor %}
        {% if spectacle.sousCategorie is not empty %}
            {{ spectacle.sousCategorie.type }} /
        {% endif %}
        {% if spectacle.sousCategoriePersonalise is not empty %}
            {{ spectacle.sousCategoriePersonalise }} /
        {% endif %}
            <p>Spectacle  <strong>{{ spectacle.spectateur }}</strong>
                {% if spectacle.ageSpectateurs is not empty %}
                    à partir de {{ spectacle.ageSpectateurs }} ans -
                {% endif %}

            {% if spectacle.duree is not empty %}
                <strong>Durée :</strong> {{ spectacle.duree }} minutes</p>
            {% endif %}

        </div>
        <div class="col-md-4 text-right ml">

                <p class="link">
                    {% if spectacle.urlVideo is not empty %}
                        <a class="link" href="{{ spectacle.urlVideo }}" target="_blank" title="Voir la bande annonce"><i class="fas fa-video"></i></a>
                    {% endif %}
                    {% if spectacle.siteCie is not empty %}
                        <a class="link" href="{{ spectacle.siteCie }}" target="_blank" title="Voir le site internet de la compagnie"><i class="fas fa-globe"></i></a>
                    {% endif %}
                    {% if spectacle.mailContact is not empty %}
                        <a class="link" href="mailto:{{ spectacle.mailContact }}?subject={{ spectacle.titre }} - demande d'informations en ligne" title="Envoyer un mail"><i class="fas fa-envelope"></i></a>
                    {% endif %}

                </p>

        </div>
    </div>
    <hr size="4" width="100%">


    <div class="text-center">
        <img  class="mt-4 img-fluid w-100" src="{{ asset('images/spectacles/' ~ spectacle.image1) }}" alt="">
    </div>

    <div class="row">
        <div class="col-md-12 text-single">
            <h6 class="mt-5 text-secondary text-uppercase">Le spectacle</h6>
            <p class="mb-2">{{ spectacle.resume|raw }}</p>
            {% if spectacle.texteComplementaire is not empty %}
                <p class="mb-2">{{ spectacle.texteComplementaire|raw }}</p>
            {% endif %}
        </div>
        <div class="col-md-12 text-single">
        {% if spectacle.noteMiseEnScene is not empty %}
                <hr size="4" width="100%">
                <h6 class="mt-3 text-secondary text-uppercase">Notes</h6>
                <p class="mb-2">{{ spectacle.noteMiseEnScene|raw }}</p>
            {% endif %}
        </div>
        <div class="col-md-12 text-single">
            {% if spectacle.atelier is not empty %}
                <hr size="4" width="100%">
                <h6 class="mt-3 text-secondary text-uppercase">Atelier</h6>
                <p>{{ spectacle.atelier|raw }}</p>
            {% endif %}
        </div>
        <div class="col-md-12 text-single">
        {% if spectacle.coproduction is not empty %}
                <hr size="4" width="100%">
                <h6 class="mt-3 text-secondary text-uppercase">Coproduction & Soutien</h6>
                <p>{{ spectacle.coproduction|raw }}</p>
            {% endif %}
        </div>
        <div class="col-md-12 text-single">
        {% if spectacle.enSavoirPlus is not empty %}
                <hr size="4" width="100%">
                <h6 class="mt-3 text-secondary text-uppercase">En savoir plus</h6>
                <p>{{ spectacle.enSavoirPlus|raw }}</p>
            {% endif %}
        </div>
        <div class="col-md-12 text-single">
        {% if spectacle.representations is not empty %}
                <hr size="4" width="100%">
                <h6 class="mt-3 text-secondary text-uppercase">Representations</h6>
                <p>{{ spectacle.representations|raw }}</p>
            {% endif %}
        </div>
    </div>
    <hr size="4" width="100%">
    <div class="row">
        <div class="col-md-6 text-single text-center">
            <h6 class="my-2 text-secondary text-uppercase">En pratique</h6>

            {% if spectacle.dossier is not empty %}
                <p>
                    <a href="{{ spectacle.dossier }}" target="_blank"><i class="fas fa-file-pdf"></i> Télécharger le dossier du spectacle</a>
                </p>
            {% endif %}
            {% if spectacle.dossierPeda is not empty %}
                <p>
                    <a href="{{ spectacle.dossierPeda }}" target="_blank"><i class="fas fa-file-pdf"></i> Télécharger le dossier du spectacle pédagogique</a>
                </p>
            {% endif %}
            {% if spectacle.enPratique is not empty %}
                <p>{{ spectacle.enPratique|raw }}</p>
            {% endif %}
            {% if spectacle.enTournee is not empty %}
                <p><strong>En tournée : </strong>{{ spectacle.enTournee|raw }}</p>
            {% endif %}

            {% if spectacle.dimensionsPlateau is not empty %}
                <p><strong>Dimensions plateau : </strong>{{ spectacle.dimensionsPlateau }}</p>
            {% endif %}
        </div>
        <div class="col-md-6 text-single text-center">
            <h6 class="my-2 text-secondary text-uppercase">La compagnie</h6>
            <p><strong>{{ spectacle.nomCie }}</strong></p>
            <p>Basée en <strong>{{ spectacle.pays }}</strong>
                {% if spectacle.departement is not empty %}
                    ({{ spectacle.departement }})
                {% endif %}
                </p>
            {% if spectacle.siteCie is not empty %}
            <p>
                <a href="{{ spectacle.siteCie }}" target="_blank"><i class="fas fa-window-restore"></i> Site de la compagnie</a>
            </p>
            {% endif %}
        </div>
    </div>

    <div class="row my-3">
        <div class="text-center col">
            <a href="mailto:{{ spectacle.mailContact }}?subject={{ spectacle.titre }} - demande d'informations en ligne" class="btn btn-outline-info">Contactez-nous</a>
        </div>
    </div>
    <div class="text-center d-flex flex-wrap">
        <div class="col-md-6">
            <img  class="mt-4 img-fluid w-100" src="{{ asset('images/spectacles/' ~ spectacle.image2) }}" alt="">
        </div>
        <div class="col-md-6">
            <img  class="mt-4 img-fluid w-100" src="{{ asset('images/spectacles/' ~ spectacle.image3) }}" alt="">
    </div>
    </div>
</div>


{% endblock %}